### ISSUE TITLE
Лицензия на сами смайлики

### ISSUE THREAD

**Issue by Chiliec** [korobochkin/VK-Emoji#1]
Что насчет лицензии на сами смайлики?

**Comment by korobochkin** [comment]
Я общался с поддержкой ВКонтакте и они сказали, что смайлики можно использовать в своих проектах. Кроме того, они сообщили, что сами их откуда то взяли. Я уточнил и напомнил, что они проводили конкурс на смайлики. Мне сообщили, что такой конкурс действительно был, но победителя не смогли выбрать, поэтому взяли уже чьи-то готовые смайлики. Кто именно автор этих смайликов мне не удалось выяснить.

Я не знаю какая лицензия на них распространяется. Я их использовал, чтобы попробовать сделать плагин для чата Candy, который бы заменял стандартные серые смайлики на вот эти.

https://github.com/candy-chat/candy

**Comment by korobochkin** [comment]
Да, и также стоит обратить внимание что здесь не все смайлики, которые, например, есть в iOS устройствах. Некоторых Emoji просто нету ВКонтакте.

**Comment by Chiliec** [comment]
Понятно, спасибо! Про *Apple Color emoji* я выяснял — лицензия подразумевает, что их [распространение нарушает авторские права](http://words.steveklabnik.com/emoji-licensing).

**Comment by korobochkin** [comment]
Хм. Что-то не верится. Я наоборот где-то читал, что эпл разрешает их перерабатывать и использовать, при условии, что там названия Apple не будет. Кроме того эпл смайлики используются даже на гитхабе :+1:

**Comment by Chiliec** [comment]
Может и так, хотя возможность использования и распространение в составе дистрибутива всё же немного разные вещи. Наверное :smirk:
